version: "3.8"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=shortlinks
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker

  redis:
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=doker

